### ISSUE TITLE
Ensure puzzle/team specific pages check their events

### ISSUE THREAD

**Issue by morganbr** [PuzzleServer/mainpuzzleserver#86] opened 2018-10-11 05:38 UTC
We have lots of puzzle and team pages that work in the context of an event, but don't check whether the input puzzle/team id is actually in the event.

**Comment by jenetlan** [comment] 2019-01-17 01:18
Duplicate of https://github.com/PuzzleServer/mainpuzzleserver/issues/107

**Closed by jenetlan** 2019-01-17 01:18 UTC
Labels: bug, duplicate
