### ISSUE TITLE
Final metapuzzle doesn't appear in puzzle list

### ISSUE THREAD

**Issue by jaylorch** [PuzzleServer/mainpuzzleserver#356] opened 2019-03-30 19:18 UTC
When I look at the list of puzzles I've authored (https://puzzlehunt.azurewebsites.net/1/author/Puzzles), my metameta doesn't appear.  It used to appear on this page, so this is a regression.

**Comment by tabascq** [comment] 2019-03-30 19:22
@jaylorch, I'm looking at the puzzle list in admin view and it's no longer there either.

**Comment by tabascq** [comment] 2019-03-30 19:25
I found it by looking at dependencies of !!! Start the Event !!!; it exists and has puzzle ID 93. I cannot explain why it is not in the list, maybe its EventID got tweaked somehow. Going to try to find it in the raw SQL.

**Comment by jaylorch** [comment] 2019-03-30 19:25
It does still exist, though, because I'm able to manually create URLs using the ID number I know it to have.  Those pages still work, e.g., the Edit or Files pages.  So I think it's just an issue with the list view.

**Comment by jaylorch** [comment] 2019-03-30 19:29
Could it have something to do with the fact that that puzzle's version number is higher than 0 (unlike the other puzzles)?  It got bumped up when I uploaded a new content file.

**Comment by jaylorch** [comment] 2019-03-30 19:30
VersionNumber is a new field with this deployment; I don't know why the list view would care about it, though.

**Comment by tabascq** [comment] 2019-03-30 19:34
The admin query is this:

                query = _context.Puzzles.Where(p => p.Event == Event);

This is why I think the EventID has been whacked somehow.

I do not know how to access the database. The connection string has fields like a password, which I do not know. @asyasky , @morganbr , @jenetlan : help needed here.

**Comment by tabascq** [comment] 2019-03-30 19:40
One more idea: There's a join at the end that looks like this:

            Puzzles = await (from Puzzle p in query
                             join ContentFile joinFile in _context.ContentFiles on p equals joinFile.Puzzle into fileJoin
                             from ContentFile file in fileJoin.DefaultIfEmpty()
                             where file == null || file.FileType  == ContentFileType.Puzzle
                             orderby p.Group, p.OrderInGroup, p.Name
                             select new PuzzleView { Puzzle = p, Content = file }).ToListAsync();

and I noticed that this puzzle has materials but no puzzle file. Maybe there is an issue with the join that causes it to get confused in this case? I don't want to randomly attach files to your puzzle, @jaylorch , but you should give that a try.

**Comment by tabascq** [comment] 2019-03-30 19:54
I have confirmed that having materials but no puzzle is the problem. I added materials to a puzzle in my local demo event and the puzzle vanished from admin, author, and player views. @morganbr , take note.

**Comment by jaylorch** [comment] 2019-03-30 20:43
Ah, thanks for working that out.  Hopefully the issue will get fixed soon.

**Comment by tabascq** [comment] 2019-03-30 20:50
Is this something you need fixed? Do you intend to have a puzzle with no primary file?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jaylorch** [comment] 2019-03-30 20:53
Yes, I have a puzzle with no primary file so I need it fixed.  I can't set a primary file for it, or else the default link will go there instead of to the custom URL I set.

**Comment by morganbr** [comment] 2019-03-30 21:29
@jaylorch, do you need a fix this weekend or is the workaround ok for a day or two?

**Comment by Vroo** [comment] 2019-03-30 21:31
I also have a puzzle with no primary file. What we want is a left outer join and I don't think `.DefaultIfEmpty()` does that. I think you need to put an empty record there. That is, `.DefaultIfEmpty(new ContentFile())`

**Comment by morganbr** [comment] 2019-03-30 21:34
The issue isn't ```DefaultIfEmpty```, it's the check for ```ContentFileType.Puzzle```. ```DefaultIfEmpty``` puts in a null ContentFile if the puzzle has no files at all, which works (and I've tested). The bug is that if the puzzle has a file that isn't ContentFileType.Puzzle (materials, solve tokens or answers), the whole thing gets filtered out. I probably need to change the outer join to not filter and then do something to get a unique set of puzzles.

**Comment by jaylorch** [comment] 2019-03-30 23:43
I've replied to Morgan's question offline about whether I need a fix this weekend.  (I don't think my answer has important spoilers, but maybe others would disagree.)

**Comment by tabascq** [comment] 2019-03-31 01:05
I think I have an easy fix for this. PR coming up.

**Comment by tabascq** [comment] 2019-03-31 01:12
The PR I posted fixes the behavior, though I'm not qualified to say whether it keeps the perf Morgan was trying to get. I *think* it does since I haven't touched the way the query returns results...

**Closed** 2019-03-31 01:40 UTC
Labels: bug
